clc;
clear all;
close all;
a=imread("images/Tulips.jpg");
b=rgb2gray(a);
a=double(b);
b=bitget(a,1);
subplot(241);imshow(b);title("Bit plane 1");
b=bitget(a,2);
subplot(242);imshow(b);title("Bit plane 2");
b=bitget(a,3);
subplot(243);imshow(b);title("Bit plane 3");
b=bitget(a,4);
subplot(244);imshow(b);title("Bit plane 4");
b=bitget(a,5);
subplot(245);imshow(b);title("Bit plane 5");
b=bitget(a,6);
subplot(246);imshow(b);title("Bit plane 6");
b=bitget(a,7);
subplot(247);imshow(b);title("Bit plane 7");
b=bitget(a,8);
subplot(248);imshow(b);title("Bit plane 8");